// frontend/src/components/Settings.tsx
import React, { useState, useEffect } from 'react';
import { X, Settings as SettingsIcon, Key, Zap, Globe } from 'lucide-react';
import './Settings.css';

interface ZackGPTConfig {
  model_name: string;
  max_tokens: number;
  temperature: number;
  voice_enabled: boolean;
  voice_model: string;
  tts_voice: string;
  memory_enabled: boolean;
  max_memory_entries: number;
  evolution_enabled: boolean;
  evolution_frequency: number;
  web_search_enabled: boolean;
  web_search_max_results: number;
  openai_api_key_masked: string;
  elevenlabs_api_key_masked: string;
  serpapi_key_masked: string;
  google_api_key_masked: string;
  google_cse_id_masked: string;
  debug_mode: boolean;
  log_level: string;
}

interface SettingsProps {
  isOpen: boolean;
  onClose: () => void;
}

const Settings: React.FC<SettingsProps> = ({ isOpen, onClose }) => {
  const [config, setConfig] = useState<ZackGPTConfig | null>(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('general');
  const [apiKeys, setApiKeys] = useState({
    openai_api_key: '',
    elevenlabs_api_key: '',
    serpapi_key: '',
    google_api_key: '',
    google_cse_id: ''
  });

  useEffect(() => {
    if (isOpen) {
      loadConfig();
    }
  }, [isOpen]);

  const loadConfig = async () => {
    setLoading(true);
    try {
      const response = await fetch('/config');
      if (response.ok) {
        const configData = await response.json();
        setConfig(configData);
      }
    } catch (error) {
      console.error('Failed to load config:', error);
    } finally {
      setLoading(false);
    }
  };

  const updateApiKeys = async () => {
    setLoading(true);
    try {
      const response = await fetch('/config/api-keys', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(apiKeys)
      });
      
      if (response.ok) {
        const result = await response.json();
        console.log('API keys updated:', result);
        loadConfig(); // Reload config to see updated masked keys
        // Clear the form
        setApiKeys({
          openai_api_key: '',
          elevenlabs_api_key: '',
          serpapi_key: '',
          google_api_key: '',
          google_cse_id: ''
        });
      }
    } catch (error) {
      console.error('Failed to update API keys:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleApiKeyChange = (key: string, value: string) => {
    setApiKeys(prev => ({ ...prev, [key]: value }));
  };

  if (!isOpen) return null;

  return (
    <div className="settings-overlay" onClick={onClose}>
      <div className="settings-modal" onClick={e => e.stopPropagation()}>
        <div className="settings-header">
          <h2>
            <SettingsIcon size={20} />
            Settings
          </h2>
          <button className="close-btn" onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="settings-content">
          <div className="settings-tabs">
            <button 
              className={`tab ${activeTab === 'general' ? 'active' : ''}`}
              onClick={() => setActiveTab('general')}
            >
              <Zap size={16} />
              General
            </button>
            <button 
              className={`tab ${activeTab === 'api-keys' ? 'active' : ''}`}
              onClick={() => setActiveTab('api-keys')}
            >
              <Key size={16} />
              API Keys
            </button>
            <button 
              className={`tab ${activeTab === 'web-search' ? 'active' : ''}`}
              onClick={() => setActiveTab('web-search')}
            >
              <Globe size={16} />
              Web Search
            </button>
          </div>

          <div className="settings-panel">
            {loading ? (
              <div className="loading">Loading...</div>
            ) : (
              <>
                {activeTab === 'general' && config && (
                  <div className="settings-section">
                    <h3>Model Configuration</h3>
                    <div className="setting-item">
                      <label>Model:</label>
                      <span className="value">{config.model_name}</span>
                    </div>
                    <div className="setting-item">
                      <label>Max Tokens:</label>
                      <span className="value">{config.max_tokens}</span>
                    </div>
                    <div className="setting-item">
                      <label>Temperature:</label>
                      <span className="value">{config.temperature}</span>
                    </div>
                    
                    <h3>Features</h3>
                    <div className="setting-item">
                      <label>Voice Enabled:</label>
                      <span className={`status ${config.voice_enabled ? 'enabled' : 'disabled'}`}>
                        {config.voice_enabled ? 'Enabled' : 'Disabled'}
                      </span>
                    </div>
                    <div className="setting-item">
                      <label>Memory Enabled:</label>
                      <span className={`status ${config.memory_enabled ? 'enabled' : 'disabled'}`}>
                        {config.memory_enabled ? 'Enabled' : 'Disabled'}
                      </span>
                    </div>
                    <div className="setting-item">
                      <label>Evolution Enabled:</label>
                      <span className={`status ${config.evolution_enabled ? 'enabled' : 'disabled'}`}>
                        {config.evolution_enabled ? 'Enabled' : 'Disabled'}
                      </span>
                    </div>
                    <div className="setting-item">
                      <label>Debug Mode:</label>
                      <span className={`status ${config.debug_mode ? 'enabled' : 'disabled'}`}>
                        {config.debug_mode ? 'Enabled' : 'Disabled'}
                      </span>
                    </div>
                  </div>
                )}

                {activeTab === 'api-keys' && config && (
                  <div className="settings-section">
                    <h3>API Keys</h3>
                    <p className="section-description">
                      Configure your API keys for various services. Keys are masked for security.
                    </p>
                    
                    <div className="api-key-form">
                      <div className="form-group">
                        <label>OpenAI API Key:</label>
                        <div className="key-display">
                          <span className="masked-key">{config.openai_api_key_masked || 'Not set'}</span>
                        </div>
                        <input
                          type="password"
                          placeholder="Enter new OpenAI API key"
                          value={apiKeys.openai_api_key}
                          onChange={(e) => handleApiKeyChange('openai_api_key', e.target.value)}
                        />
                      </div>

                      <div className="form-group">
                        <label>ElevenLabs API Key:</label>
                        <div className="key-display">
                          <span className="masked-key">{config.elevenlabs_api_key_masked || 'Not set'}</span>
                        </div>
                        <input
                          type="password"
                          placeholder="Enter new ElevenLabs API key"
                          value={apiKeys.elevenlabs_api_key}
                          onChange={(e) => handleApiKeyChange('elevenlabs_api_key', e.target.value)}
                        />
                      </div>

                      <div className="form-group">
                        <label>SerpAPI Key:</label>
                        <div className="key-display">
                          <span className="masked-key">{config.serpapi_key_masked || 'Not set'}</span>
                        </div>
                        <input
                          type="password"
                          placeholder="Enter new SerpAPI key"
                          value={apiKeys.serpapi_key}
                          onChange={(e) => handleApiKeyChange('serpapi_key', e.target.value)}
                        />
                      </div>

                      <div className="form-group">
                        <label>Google API Key:</label>
                        <div className="key-display">
                          <span className="masked-key">{config.google_api_key_masked || 'Not set'}</span>
                        </div>
                        <input
                          type="password"
                          placeholder="Enter new Google API key"
                          value={apiKeys.google_api_key}
                          onChange={(e) => handleApiKeyChange('google_api_key', e.target.value)}
                        />
                      </div>

                      <div className="form-group">
                        <label>Google CSE ID:</label>
                        <div className="key-display">
                          <span className="masked-key">{config.google_cse_id_masked || 'Not set'}</span>
                        </div>
                        <input
                          type="password"
                          placeholder="Enter new Google CSE ID"
                          value={apiKeys.google_cse_id}
                          onChange={(e) => handleApiKeyChange('google_cse_id', e.target.value)}
                        />
                      </div>

                      <button 
                        className="update-btn" 
                        onClick={updateApiKeys}
                        disabled={loading}
                      >
                        Update API Keys
                      </button>
                    </div>
                  </div>
                )}

                {activeTab === 'web-search' && config && (
                  <div className="settings-section">
                    <h3>Web Search Configuration</h3>
                    <div className="setting-item">
                      <label>Web Search Enabled:</label>
                      <span className={`status ${config.web_search_enabled ? 'enabled' : 'disabled'}`}>
                        {config.web_search_enabled ? 'Enabled' : 'Disabled'}
                      </span>
                    </div>
                    <div className="setting-item">
                      <label>Max Results:</label>
                      <span className="value">{config.web_search_max_results}</span>
                    </div>
                    
                    <h3>Search Engines Status</h3>
                    <div className="setting-item">
                      <label>SerpAPI:</label>
                      <span className={`status ${config.serpapi_key_masked ? 'configured' : 'not-configured'}`}>
                        {config.serpapi_key_masked ? 'Configured' : 'Not Configured'}
                      </span>
                    </div>
                    <div className="setting-item">
                      <label>Google Custom Search:</label>
                      <span className={`status ${config.google_api_key_masked && config.google_cse_id_masked ? 'configured' : 'not-configured'}`}>
                        {config.google_api_key_masked && config.google_cse_id_masked ? 'Configured' : 'Not Configured'}
                      </span>
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Settings;

// ui/zackgpt-ui/src/app/components/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ZackgptApiService, ZackGPTConfig } from '../../services/zackgpt-api.service';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
  config: ZackGPTConfig = {
    model_name: 'gpt-4',
    max_tokens: 2000,
    temperature: 0.7,
    voice_enabled: false,
    voice_model: 'whisper-1',
    tts_voice: 'alloy',
    memory_enabled: true,
    max_memory_entries: 1000,
    evolution_enabled: true,
    evolution_frequency: 10,
    web_search_enabled: true,
    web_search_max_results: 5,
    openai_api_key_masked: '***masked***',
    elevenlabs_api_key_masked: '***masked***',
    serpapi_key_masked: '',
    google_api_key_masked: '',
    google_cse_id_masked: '',
    debug_mode: false,
    log_level: 'INFO'
  };

  originalConfig: ZackGPTConfig = { ...this.config };
  loading = false;
  saving = false;
  isDirty = false;

  // API Key management
  apiKeys = {
    openai_api_key: '',
    elevenlabs_api_key: '',
    serpapi_key: '',
    google_api_key: '',
    google_cse_id: ''
  };
  apiKeysChanged = false;

  // Dropdown options
  logLevels = ['DEBUG', 'INFO', 'WARNING', 'ERROR'];
  ttsVoices = ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'];
  modelOptions = ['gpt-4', 'gpt-4-turbo', 'gpt-3.5-turbo'];

  constructor(private apiService: ZackgptApiService) {}

  ngOnInit(): void {
    this.loadConfig();
  }

  loadConfig(): void {
    this.loading = true;
    this.apiService.getConfig().subscribe({
      next: (config) => {
        this.config = config;
        this.originalConfig = { ...config };
        this.loading = false;
        this.checkIfDirty();
      },
      error: (error) => {
        console.error('Failed to load config:', error);
        this.loading = false;
      }
    });
  }

  saveConfig(): void {
    this.saving = true;
    
    // Save config first
    this.apiService.updateConfig(this.config).subscribe({
      next: (updatedConfig) => {
        this.config = updatedConfig;
        this.originalConfig = { ...updatedConfig };
        
        // If API keys have changed, save them too
        if (this.apiKeysChanged) {
          this.saveApiKeysInternal();
        } else {
          this.saving = false;
          this.isDirty = false;
          console.log('Config saved successfully');
        }
      },
      error: (error) => {
        console.error('Failed to save config:', error);
        this.saving = false;
      }
    });
  }

  private saveApiKeysInternal(): void {
    // Only send non-empty keys
    const keysToUpdate: {[key: string]: string} = {};
    Object.entries(this.apiKeys).forEach(([key, value]) => {
      if (value && value.trim()) {
        keysToUpdate[key] = value.trim();
      }
    });

    if (Object.keys(keysToUpdate).length === 0) {
      this.saving = false;
      this.isDirty = false;
      this.apiKeysChanged = false;
      return;
    }

    this.apiService.updateApiKeys(keysToUpdate).subscribe({
      next: (response) => {
        this.saving = false;
        this.isDirty = false;
        this.apiKeysChanged = false;
        if (response.success) {
          console.log('Config and API keys saved successfully');
          // Clear the API key fields after successful save
          this.apiKeys = {
            openai_api_key: '',
            elevenlabs_api_key: '',
            serpapi_key: '',
            google_api_key: '',
            google_cse_id: ''
          };
          // Reload config to show updated masked keys
          this.loadConfig();
        } else {
          console.error('Failed to update API keys:', response.message);
        }
      },
      error: (error) => {
        console.error('Error updating API keys:', error);
        this.saving = false;
      }
    });
  }

  resetConfig(): void {
    if (confirm('Are you sure you want to reset all settings to default values?')) {
      this.loading = true;
      this.apiService.resetConfig().subscribe({
        next: (defaultConfig) => {
          this.config = defaultConfig;
          this.originalConfig = { ...defaultConfig };
          this.loading = false;
          this.isDirty = false;
          console.log('Config reset to defaults');
        },
        error: (error) => {
          console.error('Failed to reset config:', error);
          this.loading = false;
        }
      });
    }
  }

  discardChanges(): void {
    this.config = { ...this.originalConfig };
    this.apiKeys = {
      openai_api_key: '',
      elevenlabs_api_key: '',
      serpapi_key: '',
      google_api_key: '',
      google_cse_id: ''
    };
    this.apiKeysChanged = false;
    this.isDirty = false;
  }

  onConfigChange(): void {
    this.checkIfDirty();
  }

  private checkIfDirty(): void {
    const configChanged = JSON.stringify(this.config) !== JSON.stringify(this.originalConfig);
    const apiKeysHaveValues = Object.values(this.apiKeys).some(value => value && value.trim());
    this.isDirty = configChanged || apiKeysHaveValues;
  }

  // Validation helpers
  isValidTemperature(): boolean {
    return this.config.temperature >= 0 && this.config.temperature <= 2;
  }

  isValidMaxTokens(): boolean {
    return this.config.max_tokens > 0 && this.config.max_tokens <= 8000;
  }

  isValidMemoryEntries(): boolean {
    return this.config.max_memory_entries > 0 && this.config.max_memory_entries <= 10000;
  }

  isValidEvolutionFreq(): boolean {
    return this.config.evolution_frequency > 0 && this.config.evolution_frequency <= 100;
  }

  isFormValid(): boolean {
    return this.isValidTemperature() && 
           this.isValidMaxTokens() && 
           this.isValidMemoryEntries() && 
           this.isValidEvolutionFreq() &&
           this.isValidWebSearchResults();
  }

  isValidWebSearchResults(): boolean {
    return this.config.web_search_max_results > 0 && this.config.web_search_max_results <= 20;
  }

  // API Key management methods
  onApiKeyChange(): void {
    this.apiKeysChanged = true;
    this.checkIfDirty();
  }


} 
<div class="settings-container">
  <div class="settings-header">
    <h1>⚙️ ZackGPT Settings</h1>
    <p>Configure your AI assistant's behavior and capabilities</p>
  </div>

  <div class="loading-spinner" *ngIf="loading">
    <div class="spinner"></div>
    <p>Loading configuration...</p>
  </div>

  <form *ngIf="!loading" class="settings-form">
    <!-- Core AI Settings -->
    <div class="settings-section">
      <h2>🤖 Core AI Settings</h2>
      
      <div class="form-group">
        <label for="model_name">Model</label>
        <select id="model_name" [(ngModel)]="config.model_name" (change)="onConfigChange()" name="model_name">
          <option *ngFor="let model of modelOptions" [value]="model">{{ model }}</option>
        </select>
        <small>Choose the AI model for responses</small>
      </div>

      <div class="form-group">
        <label for="max_tokens">Max Tokens</label>
        <input 
          type="number" 
          id="max_tokens" 
          [(ngModel)]="config.max_tokens" 
          (input)="onConfigChange()"
          name="max_tokens"
          min="1" 
          max="8000"
          [class.invalid]="!isValidMaxTokens()">
        <small [class.error]="!isValidMaxTokens()">
          {{ isValidMaxTokens() ? 'Maximum length of AI responses (1-8000)' : 'Must be between 1 and 8000' }}
        </small>
      </div>

      <div class="form-group">
        <label for="temperature">Temperature</label>
        <input 
          type="number" 
          id="temperature" 
          [(ngModel)]="config.temperature" 
          (input)="onConfigChange()"
          name="temperature"
          min="0" 
          max="2" 
          step="0.1"
          [class.invalid]="!isValidTemperature()">
        <small [class.error]="!isValidTemperature()">
          {{ isValidTemperature() ? 'Creativity level: 0 (focused) to 2 (creative)' : 'Must be between 0 and 2' }}
        </small>
      </div>
    </div>

    <!-- Voice Settings -->
    <div class="settings-section">
      <h2>🎙️ Voice Settings</h2>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="config.voice_enabled" 
            (change)="onConfigChange()"
            name="voice_enabled">
          <span class="checkmark"></span>
          Enable Voice Features
        </label>
        <small>Allow voice input and text-to-speech output</small>
      </div>

      <div class="form-group" *ngIf="config.voice_enabled">
        <label for="voice_model">Speech Recognition Model</label>
        <input 
          type="text" 
          id="voice_model" 
          [(ngModel)]="config.voice_model" 
          (input)="onConfigChange()"
          name="voice_model"
          placeholder="whisper-1">
        <small>OpenAI Whisper model for speech recognition</small>
      </div>

      <div class="form-group" *ngIf="config.voice_enabled">
        <label for="tts_voice">Text-to-Speech Voice</label>
        <select id="tts_voice" [(ngModel)]="config.tts_voice" (change)="onConfigChange()" name="tts_voice">
          <option *ngFor="let voice of ttsVoices" [value]="voice">{{ voice | titlecase }}</option>
        </select>
        <small>Choose the voice for spoken responses</small>
      </div>
    </div>

    <!-- Memory Settings -->
    <div class="settings-section">
      <h2>🧠 Memory Settings</h2>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="config.memory_enabled" 
            (change)="onConfigChange()"
            name="memory_enabled">
          <span class="checkmark"></span>
          Enable Memory System
        </label>
        <small>Remember conversations and learn from interactions</small>
      </div>

      <div class="form-group" *ngIf="config.memory_enabled">
        <label for="max_memory_entries">Max Memory Entries</label>
        <input 
          type="number" 
          id="max_memory_entries" 
          [(ngModel)]="config.max_memory_entries" 
          (input)="onConfigChange()"
          name="max_memory_entries"
          min="1" 
          max="10000"
          [class.invalid]="!isValidMemoryEntries()">
        <small [class.error]="!isValidMemoryEntries()">
          {{ isValidMemoryEntries() ? 'Maximum number of stored memory entries (1-10000)' : 'Must be between 1 and 10000' }}
        </small>
      </div>
    </div>

    <!-- Evolution Settings -->
    <div class="settings-section">
      <h2>🧬 Prompt Evolution Settings</h2>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="config.evolution_enabled" 
            (change)="onConfigChange()"
            name="evolution_enabled">
          <span class="checkmark"></span>
          Enable Prompt Evolution
        </label>
        <small>Allow AI to improve its prompts based on interactions</small>
      </div>

      <div class="form-group" *ngIf="config.evolution_enabled">
        <label for="evolution_frequency">Evolution Frequency</label>
        <input 
          type="number" 
          id="evolution_frequency" 
          [(ngModel)]="config.evolution_frequency" 
          (input)="onConfigChange()"
          name="evolution_frequency"
          min="1" 
          max="100"
          [class.invalid]="!isValidEvolutionFreq()">
        <small [class.error]="!isValidEvolutionFreq()">
          {{ isValidEvolutionFreq() ? 'How often to run evolution (every N interactions, 1-100)' : 'Must be between 1 and 100' }}
        </small>
      </div>
    </div>

    <!-- Web Search Settings -->
    <div class="settings-section">
      <h2>🔍 Web Search Settings</h2>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="config.web_search_enabled" 
            (change)="onConfigChange()"
            name="web_search_enabled">
          <span class="checkmark"></span>
          Enable Web Search
        </label>
        <small>Allow AI to search the internet for current information</small>
      </div>

      <div class="form-group" *ngIf="config.web_search_enabled">
        <label for="web_search_max_results">Max Search Results</label>
        <input 
          type="number" 
          id="web_search_max_results" 
          [(ngModel)]="config.web_search_max_results" 
          (input)="onConfigChange()"
          name="web_search_max_results"
          min="1" 
          max="20"
          [class.invalid]="!isValidWebSearchResults()">
        <small [class.error]="!isValidWebSearchResults()">
          {{ isValidWebSearchResults() ? 'Maximum number of search results to use (1-20)' : 'Must be between 1 and 20' }}
        </small>
      </div>

      <div class="form-group" *ngIf="config.web_search_enabled">
        <div class="api-key-status">
          <p><strong>Search Engine Status:</strong></p>
          <div class="key-status">
            <span class="key-name">SerpAPI:</span>
            <span [class]="config.serpapi_key_masked ? 'key-configured' : 'key-missing'">
              {{ config.serpapi_key_masked || 'Not configured' }}
            </span>
          </div>
          <div class="key-status">
            <span class="key-name">Google Custom Search:</span>
            <span [class]="config.google_api_key_masked && config.google_cse_id_masked ? 'key-configured' : 'key-missing'">
              {{ (config.google_api_key_masked && config.google_cse_id_masked) ? 'Configured' : 'Not configured' }}
            </span>
          </div>
          <div class="key-status">
            <span class="key-name">DuckDuckGo Fallback:</span>
            <span class="key-configured">Always available</span>
          </div>
        </div>
      </div>
    </div>

    <!-- API Keys -->
    <div class="settings-section">
      <h2>🔑 API Keys</h2>
      <p class="section-description">Enter your API keys below. Leave blank to keep existing values.</p>
      
      <div class="form-group">
        <label for="openai_key">OpenAI API Key</label>
        <input 
          type="password" 
          id="openai_key" 
          [(ngModel)]="apiKeys.openai_api_key"
          (input)="onApiKeyChange()"
          name="openai_key"
          placeholder="sk-... (leave blank to keep current)">
        <small>Required for AI responses. Current: {{ config.openai_api_key_masked || 'Not set' }}</small>
      </div>

      <div class="form-group">
        <label for="elevenlabs_key">ElevenLabs API Key</label>
        <input 
          type="password" 
          id="elevenlabs_key" 
          [(ngModel)]="apiKeys.elevenlabs_api_key"
          (input)="onApiKeyChange()"
          name="elevenlabs_key"
          placeholder="Optional - leave blank to keep current">
        <small>For voice synthesis. Current: {{ config.elevenlabs_api_key_masked || 'Not set' }}</small>
      </div>

      <div class="api-section">
        <h4>🔍 Web Search API Keys</h4>
        <p class="section-note">Choose one or more search engines for best results</p>
        
        <div class="form-group">
          <label for="serpapi_key">SerpAPI Key (Recommended)</label>
          <input 
            type="password" 
            id="serpapi_key" 
            [(ngModel)]="apiKeys.serpapi_key"
            (input)="onApiKeyChange()"
            name="serpapi_key"
            placeholder="Free tier: 100 searches/month">
          <small>
            Get free API key at <a href="https://serpapi.com" target="_blank">serpapi.com</a>. 
            Current: {{ config.serpapi_key_masked || 'Not set' }}
          </small>
        </div>

        <div class="form-group">
          <label for="google_api_key">Google API Key</label>
          <input 
            type="password" 
            id="google_api_key" 
            [(ngModel)]="apiKeys.google_api_key"
            (input)="onApiKeyChange()"
            name="google_api_key"
            placeholder="Alternative search option">
          <small>
            Get from <a href="https://console.cloud.google.com" target="_blank">Google Cloud Console</a>. 
            Current: {{ config.google_api_key_masked || 'Not set' }}
          </small>
        </div>

        <div class="form-group">
          <label for="google_cse_id">Google Custom Search Engine ID</label>
          <input 
            type="text" 
            id="google_cse_id" 
            [(ngModel)]="apiKeys.google_cse_id"
            (input)="onApiKeyChange()"
            name="google_cse_id"
            placeholder="Required with Google API Key">
          <small>
            Create at <a href="https://cse.google.com" target="_blank">cse.google.com</a>. 
            Current: {{ config.google_cse_id_masked || 'Not set' }}
          </small>
        </div>
      </div>
    </div>

    <!-- Debug Settings -->
    <div class="settings-section">
      <h2>🐛 Debug & Logging</h2>
      
      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="config.debug_mode" 
            (change)="onConfigChange()"
            name="debug_mode">
          <span class="checkmark"></span>
          Debug Mode
        </label>
        <small>Enable detailed debugging information</small>
      </div>

      <div class="form-group">
        <label for="log_level">Log Level</label>
        <select id="log_level" [(ngModel)]="config.log_level" (change)="onConfigChange()" name="log_level">
          <option *ngFor="let level of logLevels" [value]="level">{{ level }}</option>
        </select>
        <small>Choose logging verbosity level</small>
      </div>
    </div>

    <!-- Action Buttons -->
    <div class="settings-actions">
      <div class="action-buttons">
        <button 
          type="button" 
          class="btn btn-primary" 
          (click)="saveConfig()" 
          [disabled]="!isDirty || !isFormValid() || saving">
          {{ saving ? 'Saving...' : 'Save Changes' }}
        </button>
        
        <button 
          type="button" 
          class="btn btn-secondary" 
          (click)="discardChanges()" 
          [disabled]="!isDirty">
          Discard Changes
        </button>
        
        <button 
          type="button" 
          class="btn btn-danger" 
          (click)="resetConfig()">
          Reset to Defaults
        </button>
      </div>
      
      <div class="save-status" *ngIf="isDirty">
        <span class="unsaved-indicator">●</span>
        Unsaved changes
      </div>
    </div>
  </form>


</div>
